### ISSUE TITLE
Unable to obtain any result

### ISSUE THREAD

**Issue by danglotb** [Mamadou59/junit-jjoules#3]
Hello, I installed both `j-joules` and `junit-jjoules` and tried them on a toy project.

I added the annotation `@EnergyTest` to my test class and run it with `mvn clean test`.

However, I have no data in `target`, the folder `jjoules-reports` does not exist.

You can find my toy-project on GitHub [here](https://github.com/danglotb/sample) and use the following steps:

```sh
git clone https://github.com/danglotb/sample
cd sample
mvn clean test
```

Please, could you tell my what I am doing wrong?

Thank you.

**Comment by danglotb** [comment]
I did install [jjoules-maven-plugin](https://github.com/Mamadou59/jjoules-maven-plugin) and now I have the folder `jjoules-reports` with both `.csv` and `.json` files, but there are empty.

**Comment by sunssy59** [comment]
Hello Benjamin,

sorry i was taking my lunch. going to check it now.

Le jeu. 13 août 2020 à 12:57, Benjamin DANGLOT <notifications@github.com> a
écrit :

**Comment by sunssy59** [comment]
I sent you a pull request on your project sample where I made the necessary
modifications for using j-joules and junit-jjoules projects.

So what to change since our last exchange?

1) we decided to use only the two projects j-joules and junit-jjoules
because the maven plugin is already integrated in the junit-jjoules project.

 2) The branch master of junit-joules is not up to date rather use this one
https://github.com/Mamadou59/junit-jjoules/tree/callgraph

which works well I have not done the merge because I am waiting for the
confirmation of my supervisors (who are on vacation this week)  of the
different approaches used.

3) You need the call graph tool that I put on the root of your sample
project for the creation of the call graph. It is also accessible from the
junit-jjoules project in the resources directory.

4) The rule that we are also fixed is that each class of energy test must
contain only one method of energy test thing which makes it easier for us
when creating consumption reports.

Do not hesitate for any other problem I will update the README asap.

**Comment by sunssy59** [comment]
otherwise this example contains the necessary for a configuration and
writing of energy tests

   https://github.com/Mamadou59/energytest-example

**Comment by sunssy59** [comment]
Sorry I just realized that I did not send you the pull request

**Comment by danglotb** [comment]
Hello @Mamadou59 

Thank you for your support. I did manage to generate some results.

There is any visualization tool available?

**Comment by sunssy59** [comment]
Hello Benjamin,

We are on the development of a plugin for sonar which allows us to have a
visual of our results.
you can see it in this repository (
https://github.com/Mamadou59/sonar-plugin-jjoules) .

It contains a readme which explains how to build and deploy a JAR file in
sonarqube instance which run in a docker container.


For the sonar interface, you can see the analyzes by clicking on the
project then on the Measures menu and going to General.

In activity menu, with Custom option and addMetric (Energy consumed - CPU
in (μJ) , Energy consumed - dram in (μJ), Energy consumed by all test(s) in
this folder (μJ) and Duration) you can visualize on graphs the different
variations for several analyzes

And on the More menu -> Jjoules stats a web page is added to represent the
latest analysis.


Hope this helps.


Le lun. 17 août 2020 à 10:27, Benjamin DANGLOT <notifications@github.com> a
écrit :

**Comment by danglotb** [comment]
Hello @Mamadou59, thank you for the pointer. I'm giving it a try! Stay tuned :)

**Comment by danglotb** [comment]
Dear @Mamadou59 

I followed the `README` and did successfully launch Sonar with the `jjoules` plugin.

However, when I run `mvn clean test sonar:sonar`

I have the following errors:

```txt
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ sample ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running fr.inria.TestExample
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.165 sec - in fr.inria.TestExample

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:3.2.0:test-jar (default) @ sample ---
[INFO] Building jar: /home/benjamin/workspace/sample/target/sample-1.0-tests.jar
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (call-graph) @ sample ---
[INFO] 
[INFO] --- junit-jjoules:1.0-SNAPSHOT:generate-matrix (callgraph-matrix) @ sample ---
[INFO] Read tests call graph in file {tests-callgraph.txt} ...
[INFO] Create call graph matrix and dump it in file {callgraph-matrix.txt} ...
[INFO] 
[INFO] --------------------------< fr.inria:sample >---------------------------
[INFO] Building sample 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- sonar-maven-plugin:3.7.0.1746:sonar (default-cli) @ sample ---
[INFO] User cache: /home/benjamin/.sonar/cache
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.607 s
[INFO] Finished at: 2020-08-18T16:53:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project sample: Unable to execute SonarQube: Fail to parse entry in bootstrap index:
```

*EDIT* with a bunch of HTML after this error.

I have access to the web UI of Sonar from my browser at the URL `localhost:9000`. However, as expected because of the errors, there is no project.

Thank you very much! Nice job

**Comment by sunssy59** [comment]
Hello Benjamin,

I think you get this error because when you start/restart  sonarqube you
have to wait for a few seconds like 30s or more before running `mvn clean
test sonar:sonar` in your sample project.

Le mar. 18 août 2020 à 16:57, Benjamin DANGLOT <notifications@github.com> a
écrit :

**Comment by danglotb** [comment]
Okay, thank you for the answer! I keep you updated.

**Comment by danglotb** [comment]
Ok, it works fine! Thank you very much. I need something more computational intensive now :) I'll have a look at your repo.
